import type { AuctionEvent } from "@/types/domain";

export interface AuctionSourceAdapter {
  fetchActiveAuctions(): Promise<AuctionEvent[]>;
  getRefreshRate(): "realtime" | "near_realtime" | "delayed" | "daily";
  getSourceStatus(): "available" | "unavailable";
}

// Demo adapter is deliberately labelled as demo data until a licensed/API source is configured.
export const demoAuctions: AuctionEvent[] = [
  { id: "auction-1", sourceId: "ebay-demo", sourceName: "eBay（演示）", sourceRegion: "INTL", auctionUrl: "https://www.ebay.com/", playerId: "p-wemby", cardId: "card-1", playerName: "Victor Wembanyama", cardYear: 2023, manufacturer: "Panini", setName: "Prizm", parallel: "Silver RC", cardNumber: "136", rookieDesignation: true, gradingCompany: "PSA", grade: 10, currency: "USD", startingBid: 1200, currentBid: 4820, bidCount: 38, watcherCount: 94, viewCount: 1260, startTime: "2026-09-02T08:00:00Z", endTime: "2026-09-03T12:48:00Z", auctionStatus: "ending_soon", lastUpdatedAt: "2026-09-03T12:44:00Z", sourceVerified: false, saleType: "auction", heatScore: 92, heatChange24h: 18 },
  { id: "auction-2", sourceId: "goldin-demo", sourceName: "Goldin（演示）", sourceRegion: "INTL", auctionUrl: "https://goldin.co/", playerId: "p-flagg", cardId: "card-2", playerName: "Cooper Flagg", cardYear: 2025, manufacturer: "Topps", setName: "Chrome", parallel: "Refractor RC", cardNumber: "101", rookieDesignation: true, gradingCompany: "BGS", grade: 9.5, currency: "USD", startingBid: 500, currentBid: 2180, bidCount: 31, watcherCount: 72, viewCount: 884, startTime: "2026-09-01T16:00:00Z", endTime: "2026-09-04T16:00:00Z", auctionStatus: "live", lastUpdatedAt: "2026-09-03T12:40:00Z", sourceVerified: false, saleType: "auction", heatScore: 88, heatChange24h: 14 },
  { id: "auction-3", sourceId: "cardtau-demo", sourceName: "卡淘（演示）", sourceRegion: "CN", auctionUrl: "https://www.cardtau.com/", playerId: "p-luka", cardId: "card-3", playerName: "Luka Dončić", cardYear: 2018, manufacturer: "Panini", setName: "Prizm", parallel: "Silver RC", cardNumber: "280", rookieDesignation: true, gradingCompany: "PSA", grade: 10, currency: "CNY", startingBid: 9000, currentBid: 25800, bidCount: 24, watcherCount: 63, viewCount: 712, startTime: "2026-09-02T10:00:00Z", endTime: "2026-09-03T18:20:00Z", auctionStatus: "live", lastUpdatedAt: "2026-09-03T12:42:00Z", sourceVerified: false, saleType: "auction", heatScore: 84, heatChange24h: 9 },
  { id: "auction-4", sourceId: "fanatics-demo", sourceName: "Fanatics Collect（演示）", sourceRegion: "INTL", auctionUrl: "https://www.fanaticscollect.com/", playerId: "p-curry", cardId: "card-4", playerName: "Stephen Curry", cardYear: 2009, manufacturer: "Panini", setName: "National Treasures", parallel: "Auto Patch /99", cardNumber: "206", rookieDesignation: true, gradingCompany: "PSA", grade: 9, currency: "USD", startingBid: 3000, currentBid: 7450, bidCount: 19, watcherCount: 51, viewCount: 503, startTime: "2026-08-30T16:00:00Z", endTime: "2026-09-05T16:00:00Z", auctionStatus: "live", lastUpdatedAt: "2026-09-03T12:35:00Z", sourceVerified: false, saleType: "auction", heatScore: 76, heatChange24h: 6 },
  { id: "auction-5", sourceId: "heritage-demo", sourceName: "Heritage（演示）", sourceRegion: "INTL", auctionUrl: "https://www.ha.com/", playerId: "p-lebron", cardId: "card-5", playerName: "LeBron James", cardYear: 2003, manufacturer: "Topps", setName: "Chrome", parallel: "Base RC", cardNumber: "111", rookieDesignation: true, gradingCompany: "PSA", grade: 9, currency: "USD", startingBid: 10000, currentBid: 31600, bidCount: 12, watcherCount: 44, viewCount: 390, startTime: "2026-08-29T16:00:00Z", endTime: "2026-09-06T16:00:00Z", auctionStatus: "live", lastUpdatedAt: "2026-09-03T12:30:00Z", sourceVerified: false, saleType: "auction", heatScore: 69, heatChange24h: 3 },
  { id: "auction-6", sourceId: "xianyu-demo", sourceName: "闲鱼（非拍卖演示）", sourceRegion: "CN", auctionUrl: "https://www.goofish.com/", playerId: "p-harper", cardId: "card-6", playerName: "Dylan Harper", cardYear: 2025, manufacturer: "Topps", setName: "Basketball", parallel: "RC", cardNumber: "12", rookieDesignation: true, currency: "CNY", startingBid: 1800, currentBid: 1800, bidCount: 0, watcherCount: 18, viewCount: 220, startTime: "2026-09-03T10:00:00Z", endTime: "2026-09-10T10:00:00Z", auctionStatus: "live", lastUpdatedAt: "2026-09-03T12:20:00Z", sourceVerified: false, saleType: "fixed_price", heatScore: 0, heatChange24h: 0 },
];

export const activeAuctions = demoAuctions.filter((auction) => auction.saleType === "auction" && ["live", "ending_soon"].includes(auction.auctionStatus));
