import type {
  AlertRule,
  Card,
  DataSource,
  Listing,
  Player,
  PortfolioItem,
  Sale,
  Team,
} from "@/types/domain";

const teamRows = [
  [
    "atlanta-hawks",
    "ATL",
    "亚特兰大老鹰",
    "Atlanta",
    "East",
    "Southeast",
    "#e03a3e",
  ],
  [
    "boston-celtics",
    "BOS",
    "波士顿凯尔特人",
    "Boston",
    "East",
    "Atlantic",
    "#007a33",
  ],
  [
    "brooklyn-nets",
    "BKN",
    "布鲁克林篮网",
    "Brooklyn",
    "East",
    "Atlantic",
    "#8d99a6",
  ],
  [
    "charlotte-hornets",
    "CHA",
    "夏洛特黄蜂",
    "Charlotte",
    "East",
    "Southeast",
    "#1d8496",
  ],
  [
    "chicago-bulls",
    "CHI",
    "芝加哥公牛",
    "Chicago",
    "East",
    "Central",
    "#ce1141",
  ],
  [
    "cleveland-cavaliers",
    "CLE",
    "克利夫兰骑士",
    "Cleveland",
    "East",
    "Central",
    "#860038",
  ],
  [
    "dallas-mavericks",
    "DAL",
    "达拉斯独行侠",
    "Dallas",
    "West",
    "Southwest",
    "#00538c",
  ],
  [
    "denver-nuggets",
    "DEN",
    "丹佛掘金",
    "Denver",
    "West",
    "Northwest",
    "#0e2240",
  ],
  [
    "detroit-pistons",
    "DET",
    "底特律活塞",
    "Detroit",
    "East",
    "Central",
    "#c8102e",
  ],
  [
    "golden-state-warriors",
    "GSW",
    "金州勇士",
    "San Francisco",
    "West",
    "Pacific",
    "#1d428a",
  ],
  [
    "houston-rockets",
    "HOU",
    "休斯顿火箭",
    "Houston",
    "West",
    "Southwest",
    "#ce1141",
  ],
  [
    "indiana-pacers",
    "IND",
    "印第安纳步行者",
    "Indianapolis",
    "East",
    "Central",
    "#fdbb30",
  ],
  [
    "la-clippers",
    "LAC",
    "洛杉矶快船",
    "Los Angeles",
    "West",
    "Pacific",
    "#c8102e",
  ],
  [
    "los-angeles-lakers",
    "LAL",
    "洛杉矶湖人",
    "Los Angeles",
    "West",
    "Pacific",
    "#552583",
  ],
  [
    "memphis-grizzlies",
    "MEM",
    "孟菲斯灰熊",
    "Memphis",
    "West",
    "Southwest",
    "#5d76a9",
  ],
  ["miami-heat", "MIA", "迈阿密热火", "Miami", "East", "Southeast", "#98002e"],
  [
    "milwaukee-bucks",
    "MIL",
    "密尔沃基雄鹿",
    "Milwaukee",
    "East",
    "Central",
    "#00471b",
  ],
  [
    "minnesota-timberwolves",
    "MIN",
    "明尼苏达森林狼",
    "Minneapolis",
    "West",
    "Northwest",
    "#236192",
  ],
  [
    "new-orleans-pelicans",
    "NOP",
    "新奥尔良鹈鹕",
    "New Orleans",
    "West",
    "Southwest",
    "#0c2340",
  ],
  [
    "new-york-knicks",
    "NYK",
    "纽约尼克斯",
    "New York",
    "East",
    "Atlantic",
    "#f58426",
  ],
  [
    "oklahoma-city-thunder",
    "OKC",
    "俄克拉荷马城雷霆",
    "Oklahoma City",
    "West",
    "Northwest",
    "#007ac1",
  ],
  [
    "orlando-magic",
    "ORL",
    "奥兰多魔术",
    "Orlando",
    "East",
    "Southeast",
    "#0077c0",
  ],
  [
    "philadelphia-76ers",
    "PHI",
    "费城76人",
    "Philadelphia",
    "East",
    "Atlantic",
    "#006bb6",
  ],
  [
    "phoenix-suns",
    "PHX",
    "菲尼克斯太阳",
    "Phoenix",
    "West",
    "Pacific",
    "#e56020",
  ],
  [
    "portland-trail-blazers",
    "POR",
    "波特兰开拓者",
    "Portland",
    "West",
    "Northwest",
    "#e03a3e",
  ],
  [
    "sacramento-kings",
    "SAC",
    "萨克拉门托国王",
    "Sacramento",
    "West",
    "Pacific",
    "#5a2d81",
  ],
  [
    "san-antonio-spurs",
    "SAS",
    "圣安东尼奥马刺",
    "San Antonio",
    "West",
    "Southwest",
    "#9ea2a2",
  ],
  [
    "toronto-raptors",
    "TOR",
    "多伦多猛龙",
    "Toronto",
    "East",
    "Atlantic",
    "#ce1141",
  ],
  [
    "utah-jazz",
    "UTA",
    "犹他爵士",
    "Salt Lake City",
    "West",
    "Northwest",
    "#f9a01b",
  ],
  [
    "washington-wizards",
    "WAS",
    "华盛顿奇才",
    "Washington",
    "East",
    "Southeast",
    "#002b5c",
  ],
] as const;

export const teams: Team[] = teamRows.map(
  ([slug, abbreviation, name, city, conference, division, color], index) => ({
    id: `team-${index + 1}`,
    slug,
    abbreviation,
    name,
    city,
    conference,
    division,
    color,
  }),
);

const teamId = (abbr: string) =>
  teams.find((team) => team.abbreviation === abbr)?.id;

export const players: Player[] = [
  {
    id: "p-flagg",
    name: "Cooper Flagg",
    displayNameZh: "库珀·弗拉格",
    position: "F",
    draftYear: 2025,
    draftPick: 1,
    currentTeamId: teamId("DAL"),
    formerTeamIds: [],
    age: 19,
    minutes: 32.1,
    points: 19.4,
    rebounds: 7.6,
    assists: 4.1,
    marketHeat: 92,
    cohort: "core_rookie",
    isCoreRookie: true,
    isMarketActive: true,
    peerRank: 1,
    valuationSignal: "balanced",
    peerComparison: "同届演示热度第 1；成交活跃度领先，但新秀预期风险仍高。",
    injuryStatus: "healthy",
    riskLevel: "medium",
    demo: true,
  },
  {
    id: "p-harper",
    name: "Dylan Harper",
    displayNameZh: "迪伦·哈珀",
    position: "G",
    draftYear: 2025,
    draftPick: 2,
    currentTeamId: teamId("SAS"),
    formerTeamIds: [],
    age: 20,
    minutes: 29.8,
    points: 16.2,
    rebounds: 4.5,
    assists: 5.7,
    marketHeat: 84,
    cohort: "core_rookie",
    isCoreRookie: true,
    isMarketActive: true,
    peerRank: 2,
    valuationSignal: "balanced",
    peerComparison: "同届演示热度第 2；后场角色与伤病观察可能影响短期比较。",
    injuryStatus: "monitor",
    riskLevel: "medium",
    demo: true,
  },
  {
    id: "p-bailey",
    name: "Ace Bailey",
    displayNameZh: "埃斯·贝利",
    position: "F",
    draftYear: 2025,
    draftPick: 5,
    currentTeamId: teamId("UTA"),
    formerTeamIds: [],
    age: 20,
    minutes: 27.5,
    points: 14.8,
    rebounds: 5.3,
    assists: 1.9,
    marketHeat: 78,
    cohort: "core_rookie",
    isCoreRookie: true,
    isTradeHot: true,
    peerRank: 3,
    valuationSignal: "overheated",
    peerComparison: "同届演示热度第 3；低成交量使横向估值误差更大。",
    injuryStatus: "healthy",
    riskLevel: "high",
    demo: true,
  },
  {
    id: "p-dybantsa",
    name: "A.J. Dybantsa",
    displayNameZh: "A.J. 迪班萨",
    position: "F",
    draftYear: 2026,
    draftPick: 1,
    currentTeamId: teamId("WAS"),
    formerTeamIds: [],
    age: 19,
    minutes: 31.0,
    points: 18.6,
    rebounds: 6.8,
    assists: 3.4,
    marketHeat: 88,
    cohort: "core_rookie",
    isCoreRookie: true,
    isMarketActive: true,
    peerRank: 1,
    valuationSignal: "overheated",
    peerComparison: "2026 届演示关注度第 1；尚缺可信成交，不能给出精确估值。",
    injuryStatus: "healthy",
    riskLevel: "high",
    demo: true,
  },
  {
    id: "p-boozer",
    name: "Cameron Boozer",
    displayNameZh: "卡梅隆·布泽尔",
    position: "F",
    draftYear: 2026,
    draftPick: 2,
    currentTeamId: teamId("BKN"),
    formerTeamIds: [],
    age: 19,
    minutes: 30.4,
    points: 17.9,
    rebounds: 8.7,
    assists: 2.8,
    marketHeat: 82,
    cohort: "core_rookie",
    isCoreRookie: true,
    peerRank: 2,
    valuationSignal: "balanced",
    peerComparison: "2026 届演示关注度第 2；内线表现与卡市样本仍需验证。",
    injuryStatus: "healthy",
    riskLevel: "medium",
    demo: true,
  },
  {
    id: "p-peterson",
    name: "Darryn Peterson",
    displayNameZh: "达林·彼得森",
    position: "G",
    draftYear: 2026,
    draftPick: 3,
    currentTeamId: teamId("CHA"),
    formerTeamIds: [],
    age: 19,
    minutes: 28.9,
    points: 16.7,
    rebounds: 4.0,
    assists: 4.8,
    marketHeat: 77,
    cohort: "core_rookie",
    isCoreRookie: true,
    isSigningHot: true,
    peerRank: 3,
    valuationSignal: "underfollowed",
    peerComparison: "2026 届演示关注度第 3；签约热度高但伤病状态需观察。",
    injuryStatus: "monitor",
    riskLevel: "high",
    demo: true,
  },
  {
    id: "p-wemby",
    name: "Victor Wembanyama",
    displayNameZh: "维克托·文班亚马",
    position: "C-F",
    draftYear: 2023,
    draftPick: 1,
    currentTeamId: teamId("SAS"),
    formerTeamIds: [],
    age: 22,
    minutes: 33.2,
    points: 24.7,
    rebounds: 10.9,
    assists: 3.8,
    marketHeat: 96,
    cohort: "recent_rookie",
    isMarketActive: true,
    peerRank: 1,
    valuationSignal: "balanced",
    peerComparison: "2023 届演示热度第 1；与相邻选秀届相比成交深度更高。",
    injuryStatus: "monitor",
    riskLevel: "medium",
    demo: true,
  },
  {
    id: "p-edwards",
    name: "Anthony Edwards",
    displayNameZh: "安东尼·爱德华兹",
    position: "G",
    draftYear: 2020,
    draftPick: 1,
    currentTeamId: teamId("MIN"),
    formerTeamIds: [],
    age: 25,
    minutes: 35.1,
    points: 27.6,
    rebounds: 5.7,
    assists: 5.1,
    marketHeat: 91,
    cohort: "young_core",
    isMarketActive: true,
    peerRank: 1,
    valuationSignal: "balanced",
    peerComparison: "2020 届代表性年轻核心；高端 RPA 流动性低于普卡。",
    injuryStatus: "healthy",
    riskLevel: "low",
    demo: true,
  },
  {
    id: "p-haliburton",
    name: "Tyrese Haliburton",
    displayNameZh: "泰瑞斯·哈利伯顿",
    position: "G",
    draftYear: 2020,
    draftPick: 12,
    currentTeamId: teamId("IND"),
    formerTeamIds: [teamId("SAC")!],
    age: 26,
    minutes: 34.0,
    points: 19.1,
    rebounds: 3.8,
    assists: 9.2,
    marketHeat: 83,
    cohort: "young_core",
    isMarketActive: true,
    peerRank: 2,
    valuationSignal: "underfollowed",
    peerComparison: "2020 届演示热度第 2；后卫卡需求与伤病恢复节奏相关。",
    injuryStatus: "monitor",
    riskLevel: "medium",
    demo: true,
  },
  {
    id: "p-cade",
    name: "Cade Cunningham",
    displayNameZh: "凯德·坎宁安",
    position: "G",
    draftYear: 2021,
    draftPick: 1,
    currentTeamId: teamId("DET"),
    formerTeamIds: [],
    age: 24,
    minutes: 35.0,
    points: 25.4,
    rebounds: 6.1,
    assists: 9.0,
    marketHeat: 86,
    cohort: "young_core",
    isMarketActive: true,
    peerRank: 1,
    valuationSignal: "balanced",
    peerComparison: "2021 届演示热度第 1；年轻核心标签高于普通近年新秀。",
    injuryStatus: "healthy",
    riskLevel: "medium",
    demo: true,
  },
  {
    id: "p-barnes",
    name: "Scottie Barnes",
    displayNameZh: "斯科蒂·巴恩斯",
    position: "F",
    draftYear: 2021,
    draftPick: 4,
    currentTeamId: teamId("TOR"),
    formerTeamIds: [],
    age: 25,
    minutes: 34.1,
    points: 20.0,
    rebounds: 7.8,
    assists: 6.0,
    marketHeat: 74,
    cohort: "young_core",
    isMarketActive: true,
    peerRank: 2,
    valuationSignal: "underfollowed",
    peerComparison:
      "2021 届演示热度第 2；多面手表现稳定，卡市关注度低于同届榜首。",
    injuryStatus: "healthy",
    riskLevel: "low",
    demo: true,
  },
  {
    id: "p-paolo",
    name: "Paolo Banchero",
    displayNameZh: "保罗·班凯罗",
    position: "F",
    draftYear: 2022,
    draftPick: 1,
    currentTeamId: teamId("ORL"),
    formerTeamIds: [],
    age: 23,
    minutes: 34.4,
    points: 24.8,
    rebounds: 7.4,
    assists: 5.0,
    marketHeat: 87,
    cohort: "recent_rookie",
    isMarketActive: true,
    peerRank: 1,
    valuationSignal: "balanced",
    peerComparison: "2022 届演示热度第 1；与 2023/2024 榜首相比成交量居中。",
    injuryStatus: "healthy",
    riskLevel: "medium",
    demo: true,
  },
  {
    id: "p-chet",
    name: "Chet Holmgren",
    displayNameZh: "切特·霍姆格伦",
    position: "C-F",
    draftYear: 2022,
    draftPick: 2,
    currentTeamId: teamId("OKC"),
    formerTeamIds: [],
    age: 24,
    minutes: 31.6,
    points: 18.2,
    rebounds: 8.6,
    assists: 2.7,
    marketHeat: 81,
    cohort: "recent_rookie",
    isMarketActive: true,
    peerRank: 2,
    valuationSignal: "balanced",
    peerComparison:
      "2022 届演示热度第 2；伤病历史与球队竞争结构是主要比较变量。",
    injuryStatus: "monitor",
    riskLevel: "medium",
    demo: true,
  },
  {
    id: "p-miller",
    name: "Brandon Miller",
    displayNameZh: "布兰登·米勒",
    position: "F",
    draftYear: 2023,
    draftPick: 2,
    currentTeamId: teamId("CHA"),
    formerTeamIds: [],
    age: 23,
    minutes: 33.3,
    points: 21.4,
    rebounds: 5.2,
    assists: 3.8,
    marketHeat: 76,
    cohort: "recent_rookie",
    isTradeHot: true,
    peerRank: 2,
    valuationSignal: "underfollowed",
    peerComparison: "2023 届演示热度第 2；与同届榜首存在明显关注度差距。",
    injuryStatus: "monitor",
    riskLevel: "high",
    demo: true,
  },
  {
    id: "p-risacher",
    name: "Zaccharie Risacher",
    displayNameZh: "扎卡里·里萨谢",
    position: "F",
    draftYear: 2024,
    draftPick: 1,
    currentTeamId: teamId("ATL"),
    formerTeamIds: [],
    age: 21,
    minutes: 29.6,
    points: 15.8,
    rebounds: 4.6,
    assists: 2.1,
    marketHeat: 79,
    cohort: "recent_rookie",
    peerRank: 1,
    valuationSignal: "balanced",
    peerComparison:
      "2024 届演示热度第 1；相较 2025 核心新秀，市场关注度仍偏低。",
    injuryStatus: "healthy",
    riskLevel: "medium",
    demo: true,
  },
  {
    id: "p-sarr",
    name: "Alex Sarr",
    displayNameZh: "亚历克斯·萨尔",
    position: "C-F",
    draftYear: 2024,
    draftPick: 2,
    currentTeamId: teamId("WAS"),
    formerTeamIds: [],
    age: 21,
    minutes: 30.2,
    points: 15.2,
    rebounds: 8.1,
    assists: 2.4,
    marketHeat: 73,
    cohort: "recent_rookie",
    isMarketActive: true,
    peerRank: 2,
    valuationSignal: "underfollowed",
    peerComparison: "2024 届演示热度第 2；内线卡种成交样本通常更稀疏。",
    injuryStatus: "healthy",
    riskLevel: "medium",
    demo: true,
  },
  {
    id: "p-white",
    name: "Derrick White",
    displayNameZh: "德里克·怀特",
    position: "G",
    draftYear: 2017,
    draftPick: 29,
    currentTeamId: teamId("BOS"),
    formerTeamIds: [teamId("SAS")!],
    age: 32,
    minutes: 32.7,
    points: 17.1,
    rebounds: 4.2,
    assists: 4.7,
    marketHeat: 66,
    cohort: "prime",
    isRolePlayer: true,
    isSigningHot: true,
    valuationSignal: "underfollowed",
    peerComparison: "角色球员组市场热度中等，价格更依赖季后赛表现与球队角色。",
    injuryStatus: "healthy",
    riskLevel: "medium",
    demo: true,
  },
  {
    id: "p-bridges",
    name: "Mikal Bridges",
    displayNameZh: "米卡尔·布里奇斯",
    position: "F",
    draftYear: 2018,
    draftPick: 10,
    currentTeamId: teamId("NYK"),
    formerTeamIds: [teamId("PHX")!, teamId("BKN")!],
    age: 30,
    minutes: 34.8,
    points: 18.3,
    rebounds: 4.0,
    assists: 3.6,
    marketHeat: 71,
    cohort: "prime",
    isRolePlayer: true,
    isTradeHot: true,
    isMarketActive: true,
    valuationSignal: "balanced",
    peerComparison: "交易热门角色组关注度更受球队变化驱动，需警惕短期炒作。",
    injuryStatus: "healthy",
    riskLevel: "medium",
    demo: true,
  },
  {
    id: "p-curry",
    name: "Stephen Curry",
    displayNameZh: "斯蒂芬·库里",
    position: "G",
    draftYear: 2009,
    draftPick: 7,
    currentTeamId: teamId("GSW"),
    formerTeamIds: [],
    age: 38,
    minutes: 32.5,
    points: 26.0,
    rebounds: 4.5,
    assists: 6.1,
    marketHeat: 95,
    cohort: "veteran",
    isMarketActive: true,
    valuationSignal: "balanced",
    peerComparison: "老将组收藏认知高，稀有卡与普卡的流动性分化明显。",
    injuryStatus: "healthy",
    riskLevel: "medium",
    demo: true,
  },
  {
    id: "p-lebron",
    name: "LeBron James",
    displayNameZh: "勒布朗·詹姆斯",
    position: "F",
    draftYear: 2003,
    draftPick: 1,
    currentTeamId: teamId("LAL"),
    formerTeamIds: [teamId("CLE")!, teamId("MIA")!],
    age: 41,
    minutes: 33.4,
    points: 22.9,
    rebounds: 7.1,
    assists: 7.4,
    marketHeat: 94,
    cohort: "veteran",
    isMarketActive: true,
    isSigningHot: true,
    valuationSignal: "balanced",
    peerComparison: "老将组历史需求强，但状态、供给与退役时间预期会影响波动。",
    injuryStatus: "monitor",
    riskLevel: "medium",
    demo: true,
  },
  {
    id: "p-jordan",
    name: "Michael Jordan",
    displayNameZh: "迈克尔·乔丹",
    position: "G",
    draftYear: 1984,
    draftPick: 3,
    formerTeamIds: [teamId("CHI")!, teamId("WAS")!],
    age: 63,
    minutes: 0,
    points: 30.1,
    rebounds: 6.2,
    assists: 5.3,
    marketHeat: 97,
    cohort: "retired_legend",
    isMarketActive: true,
    valuationSignal: "balanced",
    peerComparison: "退役传奇组长期收藏认知高，单一卡种成交深度差异显著。",
    injuryStatus: "healthy",
    riskLevel: "low",
    demo: true,
  },
];

const makeIdentity = (card: Omit<Card, "identityKey">) =>
  [
    card.brand,
    card.productLine,
    card.releaseYear,
    card.cardNumber,
    card.playerId,
    card.parallel,
    card.printRun ?? "unlimited",
    card.autographType ?? "none",
    card.materialType ?? "none",
    card.gradingCompany ?? "raw",
    card.grade ?? "raw",
  ]
    .join("|")
    .toLowerCase();
const card = (input: Omit<Card, "identityKey">): Card => ({
  ...input,
  identityKey: makeIdentity(input),
});

export const cards: Card[] = [
  card({
    id: "1",
    playerId: "p-flagg",
    releaseYear: 2025,
    draftYear: 2025,
    brand: "Topps",
    productLine: "Topps Chrome Basketball",
    cardNumber: "#101",
    rookie: true,
    type: "Parallel",
    parallel: "Refractor",
    color: "Silver",
    autograph: false,
    memorabilia: false,
    condition: "graded",
    gradingCompany: "PSA",
    grade: 10,
    printedTeamId: teamId("DAL"),
    latestSaleCny: 8420,
    latestListingCny: 9280,
    change7d: 12.8,
    change30d: 21.4,
    change90d: 34.1,
    sales30d: 14,
    listingsCount: 8,
    liquidity: 82,
    riskLevel: "medium",
    matchConfidence: 96,
    dataCompleteness: 91,
    demo: true,
  }),
  card({
    id: "2",
    playerId: "p-wemby",
    releaseYear: 2023,
    draftYear: 2023,
    brand: "Panini",
    productLine: "Prizm",
    cardNumber: "#136",
    rookie: true,
    type: "Parallel",
    parallel: "Silver Prizm",
    color: "Silver",
    autograph: false,
    memorabilia: false,
    condition: "graded",
    gradingCompany: "PSA",
    grade: 10,
    printedTeamId: teamId("SAS"),
    latestSaleCny: 6780,
    latestListingCny: 7350,
    change7d: 7.4,
    change30d: 5.2,
    change90d: -3.9,
    change1y: 18.4,
    sales30d: 28,
    listingsCount: 31,
    liquidity: 91,
    riskLevel: "medium",
    matchConfidence: 99,
    dataCompleteness: 97,
    demo: true,
  }),
  card({
    id: "3",
    playerId: "p-harper",
    releaseYear: 2025,
    draftYear: 2025,
    brand: "Topps",
    productLine: "Topps Basketball",
    cardNumber: "#202",
    rookie: true,
    type: "Base",
    parallel: "Base",
    autograph: false,
    memorabilia: false,
    condition: "raw",
    printedTeamId: teamId("SAS"),
    latestSaleCny: 2160,
    latestListingCny: 2450,
    change7d: 5.9,
    change30d: 9.8,
    sales30d: 19,
    listingsCount: 22,
    liquidity: 76,
    riskLevel: "low",
    matchConfidence: 95,
    dataCompleteness: 88,
    demo: true,
  }),
  card({
    id: "4",
    playerId: "p-bailey",
    releaseYear: 2025,
    draftYear: 2025,
    brand: "Topps",
    productLine: "Topps Finest",
    cardNumber: "#88",
    rookie: true,
    type: "Parallel",
    parallel: "Gold Refractor",
    color: "Gold",
    printRun: 50,
    autograph: true,
    autographType: "Sticker",
    memorabilia: false,
    condition: "graded",
    gradingCompany: "BGS",
    grade: 9.5,
    printedTeamId: teamId("UTA"),
    latestSaleCny: 3350,
    latestListingCny: 4180,
    change7d: -4.6,
    change30d: -9.1,
    sales30d: 3,
    listingsCount: 2,
    liquidity: 38,
    riskLevel: "high",
    matchConfidence: 91,
    dataCompleteness: 73,
    demo: true,
  }),
  card({
    id: "5",
    playerId: "p-edwards",
    releaseYear: 2020,
    draftYear: 2020,
    brand: "Panini",
    productLine: "National Treasures",
    cardNumber: "#130",
    rookie: true,
    type: "Patch",
    parallel: "Rookie Patch Auto",
    printRun: 99,
    autograph: true,
    autographType: "On-card",
    memorabilia: true,
    materialType: "Player-worn patch",
    condition: "graded",
    gradingCompany: "PSA",
    grade: 9,
    printedTeamId: teamId("MIN"),
    latestSaleCny: 46800,
    latestListingCny: 55200,
    change7d: 1.4,
    change30d: 8.2,
    change90d: 12.5,
    sales30d: 2,
    listingsCount: 4,
    liquidity: 31,
    riskLevel: "high",
    matchConfidence: 98,
    dataCompleteness: 86,
    demo: true,
  }),
  card({
    id: "6",
    playerId: "p-jordan",
    releaseYear: 1996,
    draftYear: 1984,
    brand: "Upper Deck",
    productLine: "SPx",
    cardNumber: "#8",
    rookie: false,
    type: "Insert",
    parallel: "Hologram",
    autograph: false,
    memorabilia: false,
    condition: "graded",
    gradingCompany: "PSA",
    grade: 9,
    printedTeamId: teamId("CHI"),
    latestSaleCny: 12800,
    latestListingCny: 14600,
    change7d: 0.8,
    change30d: 2.1,
    change1y: 9.7,
    sales30d: 6,
    listingsCount: 9,
    liquidity: 64,
    riskLevel: "low",
    matchConfidence: 97,
    dataCompleteness: 89,
    demo: true,
  }),
  card({
    id: "7",
    playerId: "p-dybantsa",
    releaseYear: 2026,
    draftYear: 2026,
    brand: "Topps",
    productLine: "Topps Chrome Basketball",
    cardNumber: "#1",
    rookie: true,
    type: "Auto",
    parallel: "Blue Auto",
    color: "Blue",
    printRun: 150,
    autograph: true,
    autographType: "On-card",
    memorabilia: false,
    condition: "raw",
    printedTeamId: teamId("WAS"),
    latestListingCny: 6100,
    sales30d: 0,
    listingsCount: 3,
    liquidity: 12,
    riskLevel: "high",
    matchConfidence: 78,
    dataCompleteness: 42,
    demo: true,
  }),
  card({
    id: "8",
    playerId: "p-cade",
    releaseYear: 2021,
    draftYear: 2021,
    brand: "Panini",
    productLine: "Prizm",
    cardNumber: "#282",
    rookie: true,
    type: "Base",
    parallel: "Base",
    autograph: false,
    memorabilia: false,
    condition: "graded",
    gradingCompany: "PSA",
    grade: 10,
    printedTeamId: teamId("DET"),
    latestSaleCny: 1380,
    latestListingCny: 1590,
    change7d: 3.4,
    change30d: 11.2,
    change90d: 19.8,
    change1y: 31.0,
    sales30d: 11,
    listingsCount: 18,
    liquidity: 72,
    riskLevel: "medium",
    matchConfidence: 97,
    dataCompleteness: 90,
    demo: true,
  }),
  card({
    id: "9",
    playerId: "p-paolo",
    releaseYear: 2022,
    draftYear: 2022,
    brand: "Panini",
    productLine: "Select",
    cardNumber: "#201",
    rookie: true,
    type: "Parallel",
    parallel: "Silver Prizm",
    color: "Silver",
    autograph: false,
    memorabilia: false,
    condition: "graded",
    gradingCompany: "PSA",
    grade: 10,
    printedTeamId: teamId("ORL"),
    latestSaleCny: 2280,
    latestListingCny: 2590,
    change7d: 2.8,
    change30d: 7.6,
    change90d: 13.1,
    change1y: 22.4,
    sales30d: 13,
    listingsCount: 16,
    liquidity: 77,
    riskLevel: "medium",
    matchConfidence: 96,
    dataCompleteness: 92,
    demo: true,
  }),
  card({
    id: "10",
    playerId: "p-miller",
    releaseYear: 2023,
    draftYear: 2023,
    brand: "Panini",
    productLine: "Donruss Optic",
    cardNumber: "#225",
    rookie: true,
    type: "Parallel",
    parallel: "Holo",
    color: "Silver",
    autograph: false,
    memorabilia: false,
    condition: "graded",
    gradingCompany: "PSA",
    grade: 10,
    printedTeamId: teamId("CHA"),
    latestSaleCny: 960,
    latestListingCny: 1180,
    change7d: -2.1,
    change30d: -6.4,
    change90d: 1.8,
    sales30d: 7,
    listingsCount: 12,
    liquidity: 58,
    riskLevel: "high",
    matchConfidence: 95,
    dataCompleteness: 82,
    demo: true,
  }),
  card({
    id: "11",
    playerId: "p-risacher",
    releaseYear: 2024,
    draftYear: 2024,
    brand: "Panini",
    productLine: "Prizm",
    cardNumber: "#251",
    rookie: true,
    type: "Parallel",
    parallel: "Silver Prizm",
    color: "Silver",
    autograph: false,
    memorabilia: false,
    condition: "graded",
    gradingCompany: "PSA",
    grade: 10,
    printedTeamId: teamId("ATL"),
    latestSaleCny: 780,
    latestListingCny: 950,
    change7d: 4.2,
    change30d: 6.1,
    change90d: 8.8,
    sales30d: 8,
    listingsCount: 13,
    liquidity: 62,
    riskLevel: "medium",
    matchConfidence: 94,
    dataCompleteness: 80,
    demo: true,
  }),
  card({
    id: "12",
    playerId: "p-chet",
    releaseYear: 2022,
    draftYear: 2022,
    brand: "Panini",
    productLine: "Prizm",
    cardNumber: "#266",
    rookie: true,
    type: "Parallel",
    parallel: "Red Ice",
    color: "Red",
    autograph: false,
    memorabilia: false,
    condition: "graded",
    gradingCompany: "PSA",
    grade: 10,
    printedTeamId: teamId("OKC"),
    latestSaleCny: 1640,
    latestListingCny: 1880,
    change7d: 1.3,
    change30d: 4.7,
    change90d: 9.4,
    sales30d: 9,
    listingsCount: 10,
    liquidity: 67,
    riskLevel: "medium",
    matchConfidence: 96,
    dataCompleteness: 87,
    demo: true,
  }),
  card({
    id: "13",
    playerId: "p-barnes",
    releaseYear: 2021,
    draftYear: 2021,
    brand: "Panini",
    productLine: "Mosaic",
    cardNumber: "#215",
    rookie: true,
    type: "Parallel",
    parallel: "Genesis",
    autograph: false,
    memorabilia: false,
    condition: "raw",
    printedTeamId: teamId("TOR"),
    latestSaleCny: 1120,
    latestListingCny: 1390,
    change7d: 0.6,
    change30d: 3.2,
    sales30d: 5,
    listingsCount: 7,
    liquidity: 49,
    riskLevel: "low",
    matchConfidence: 92,
    dataCompleteness: 78,
    demo: true,
  }),
  card({
    id: "14",
    playerId: "p-haliburton",
    releaseYear: 2020,
    draftYear: 2020,
    brand: "Panini",
    productLine: "Donruss Optic",
    cardNumber: "#153",
    rookie: true,
    type: "Parallel",
    parallel: "Holo",
    autograph: false,
    memorabilia: false,
    condition: "graded",
    gradingCompany: "PSA",
    grade: 10,
    printedTeamId: teamId("SAC"),
    latestSaleCny: 1260,
    latestListingCny: 1490,
    change7d: -1.7,
    change30d: -3.8,
    change90d: 5.3,
    sales30d: 6,
    listingsCount: 9,
    liquidity: 55,
    riskLevel: "medium",
    matchConfidence: 97,
    dataCompleteness: 84,
    demo: true,
  }),
  card({
    id: "15",
    playerId: "p-white",
    releaseYear: 2017,
    draftYear: 2017,
    brand: "Panini",
    productLine: "Prizm",
    cardNumber: "#291",
    rookie: true,
    type: "Base",
    parallel: "Base",
    autograph: false,
    memorabilia: false,
    condition: "graded",
    gradingCompany: "PSA",
    grade: 10,
    printedTeamId: teamId("SAS"),
    latestSaleCny: 520,
    latestListingCny: 680,
    change7d: 6.8,
    change30d: 14.0,
    sales30d: 4,
    listingsCount: 6,
    liquidity: 46,
    riskLevel: "medium",
    matchConfidence: 96,
    dataCompleteness: 76,
    demo: true,
  }),
  card({
    id: "16",
    playerId: "p-bridges",
    releaseYear: 2018,
    draftYear: 2018,
    brand: "Panini",
    productLine: "Prizm",
    cardNumber: "#289",
    rookie: true,
    type: "Parallel",
    parallel: "Silver Prizm",
    autograph: false,
    memorabilia: false,
    condition: "graded",
    gradingCompany: "PSA",
    grade: 10,
    printedTeamId: teamId("PHX"),
    latestSaleCny: 740,
    latestListingCny: 920,
    change7d: 4.1,
    change30d: 9.5,
    sales30d: 5,
    listingsCount: 8,
    liquidity: 51,
    riskLevel: "medium",
    matchConfidence: 96,
    dataCompleteness: 81,
    demo: true,
  }),
  card({
    id: "17",
    playerId: "p-curry",
    releaseYear: 2009,
    draftYear: 2009,
    brand: "Topps",
    productLine: "Topps Basketball",
    cardNumber: "#321",
    rookie: true,
    type: "Base",
    parallel: "Base",
    autograph: false,
    memorabilia: false,
    condition: "graded",
    gradingCompany: "PSA",
    grade: 9,
    printedTeamId: teamId("GSW"),
    latestSaleCny: 98600,
    latestListingCny: 108000,
    change7d: 1.0,
    change30d: 4.8,
    change90d: 12.1,
    change1y: 17.6,
    sales30d: 3,
    listingsCount: 5,
    liquidity: 39,
    riskLevel: "medium",
    matchConfidence: 99,
    dataCompleteness: 91,
    demo: true,
  }),
  card({
    id: "18",
    playerId: "p-sarr",
    releaseYear: 2024,
    draftYear: 2024,
    brand: "Panini",
    productLine: "Select",
    cardNumber: "#202",
    rookie: true,
    type: "Parallel",
    parallel: "Blue Scope",
    color: "Blue",
    autograph: false,
    memorabilia: false,
    condition: "raw",
    printedTeamId: teamId("WAS"),
    latestSaleCny: 610,
    latestListingCny: 790,
    change7d: 2.0,
    change30d: 5.0,
    sales30d: 4,
    listingsCount: 6,
    liquidity: 44,
    riskLevel: "medium",
    matchConfidence: 91,
    dataCompleteness: 71,
    demo: true,
  }),
];

export const dataSources: DataSource[] = [
  {
    id: "src-cardhobby",
    name: "卡淘 CardHobby",
    region: "CN",
    enabled: false,
    requiresApiKey: false,
    supportsListings: false,
    supportsSales: false,
    authorization: "adapter-only",
    error: "等待商业授权或 CSV 导入",
  },
  {
    id: "src-xianyu",
    name: "闲鱼",
    region: "CN",
    enabled: false,
    requiresApiKey: false,
    supportsListings: false,
    supportsSales: false,
    authorization: "adapter-only",
    error: "未授权，不进行自动采集",
  },
  {
    id: "src-carousell",
    name: "Carousell Hong Kong",
    region: "HK",
    enabled: false,
    requiresApiKey: false,
    supportsListings: false,
    supportsSales: false,
    authorization: "adapter-only",
    error: "未授权，仅保留适配器",
  },
  {
    id: "src-ebay",
    name: "eBay Browse API",
    region: "INTL",
    enabled: false,
    requiresApiKey: true,
    supportsListings: true,
    supportsSales: false,
    authorization: "official-api",
    error: "缺少 EBAY_CLIENT_ID",
  },
  {
    id: "src-community",
    name: "社区提交",
    region: "COMMUNITY",
    enabled: true,
    requiresApiKey: false,
    supportsListings: false,
    supportsSales: true,
    authorization: "community",
    lastSyncAt: "2026-08-31T01:30:00Z",
  },
  {
    id: "src-demo",
    name: "Nucleus 演示源",
    region: "COMMUNITY",
    enabled: true,
    requiresApiKey: false,
    supportsListings: true,
    supportsSales: true,
    authorization: "demo",
    lastSyncAt: "2026-08-31T01:30:00Z",
  },
];

export const sales: Sale[] = [
  {
    id: "sale-1",
    cardId: "1",
    sourceId: "src-demo",
    soldAt: "2026-08-30T12:20:00Z",
    originalAmount: 8420,
    originalCurrency: "CNY",
    convertedCny: 8420,
    exchangeRate: 1,
    verified: true,
    communitySubmitted: false,
    isBundle: false,
    isOutlier: false,
  },
  {
    id: "sale-2",
    cardId: "1",
    sourceId: "src-demo",
    soldAt: "2026-08-27T08:12:00Z",
    originalAmount: 8750,
    originalCurrency: "HKD",
    convertedCny: 8015,
    exchangeRate: 0.916,
    verified: true,
    communitySubmitted: false,
    isBundle: false,
    isOutlier: false,
  },
  {
    id: "sale-3",
    cardId: "1",
    sourceId: "src-community",
    soldAt: "2026-08-24T14:04:00Z",
    originalAmount: 1100,
    originalCurrency: "USD",
    convertedCny: 7887,
    exchangeRate: 7.17,
    verified: false,
    communitySubmitted: true,
    isBundle: false,
    isOutlier: false,
  },
  {
    id: "sale-4",
    cardId: "1",
    sourceId: "src-demo",
    soldAt: "2026-08-21T02:31:00Z",
    originalAmount: 7800,
    originalCurrency: "CNY",
    convertedCny: 7800,
    exchangeRate: 1,
    verified: true,
    communitySubmitted: false,
    isBundle: false,
    isOutlier: false,
  },
  {
    id: "sale-5",
    cardId: "1",
    sourceId: "src-demo",
    soldAt: "2026-08-19T18:44:00Z",
    originalAmount: 19999,
    originalCurrency: "CNY",
    convertedCny: 19999,
    exchangeRate: 1,
    verified: true,
    communitySubmitted: false,
    isBundle: false,
    isOutlier: true,
    excludedReason: "偏离 30 日中位数超过 2.5× IQR",
  },
  {
    id: "sale-6",
    cardId: "2",
    sourceId: "src-demo",
    soldAt: "2026-08-29T12:20:00Z",
    originalAmount: 6780,
    originalCurrency: "CNY",
    convertedCny: 6780,
    exchangeRate: 1,
    verified: true,
    communitySubmitted: false,
    isBundle: false,
    isOutlier: false,
  },
  {
    id: "sale-7",
    cardId: "2",
    sourceId: "src-demo",
    soldAt: "2026-08-23T12:20:00Z",
    originalAmount: 920,
    originalCurrency: "USD",
    convertedCny: 6596,
    exchangeRate: 7.17,
    verified: true,
    communitySubmitted: false,
    isBundle: false,
    isOutlier: false,
  },
  {
    id: "sale-8",
    cardId: "4",
    sourceId: "src-community",
    soldAt: "2026-08-16T12:20:00Z",
    originalAmount: 3350,
    originalCurrency: "CNY",
    convertedCny: 3350,
    exchangeRate: 1,
    verified: false,
    communitySubmitted: true,
    isBundle: false,
    isOutlier: false,
  },
  ...cards
    .filter(
      (item) =>
        item.latestSaleCny != null && !["1", "2", "4"].includes(item.id),
    )
    .map((item, index): Sale => ({
      id: `sale-baseline-${item.id}`,
      cardId: item.id,
      sourceId: "src-demo",
      soldAt: `2026-08-${String(10 + (index % 18)).padStart(2, "0")}T09:00:00Z`,
      originalAmount: item.latestSaleCny!,
      originalCurrency: "CNY",
      convertedCny: item.latestSaleCny!,
      exchangeRate: 1,
      verified: true,
      communitySubmitted: false,
      isBundle: false,
      isOutlier: false,
    })),
];

export const listings: Listing[] = cards
  .filter((item) => item.latestListingCny)
  .map((item, index) => ({
    id: `listing-${index + 1}`,
    cardId: item.id,
    sourceId: "src-demo",
    listedAt: "2026-08-31T01:30:00Z",
    amount: item.latestListingCny!,
    currency: "CNY",
    convertedCny: item.latestListingCny!,
  }));

export const demoPortfolio: PortfolioItem[] = [
  {
    id: "holding-1",
    cardId: "1",
    quantity: 1,
    purchasePrice: 6900,
    purchaseCurrency: "CNY",
    purchaseDate: "2026-06-18",
    platform: "卡展线下",
    fees: 0,
    shipping: 35,
    tax: 0,
    gradingCost: 0,
    note: "演示持仓",
    isPublic: true,
  },
  {
    id: "holding-2",
    cardId: "2",
    quantity: 2,
    purchasePrice: 5800,
    purchaseCurrency: "CNY",
    purchaseDate: "2026-04-12",
    platform: "eBay",
    fees: 320,
    shipping: 180,
    tax: 0,
    gradingCost: 0,
    note: "长期收藏",
    isPublic: true,
  },
  {
    id: "holding-3",
    cardId: "5",
    quantity: 1,
    purchasePrice: 42000,
    purchaseCurrency: "CNY",
    purchaseDate: "2025-11-02",
    platform: "拍卖行",
    fees: 2100,
    shipping: 260,
    tax: 0,
    gradingCost: 0,
    note: "隐藏成本演示",
    isPublic: false,
  },
];

export const demoAlerts: AlertRule[] = [
  {
    id: "alert-1",
    cardId: "1",
    type: "price_above",
    threshold: 8500,
    enabled: true,
    triggered: false,
  },
  {
    id: "alert-2",
    cardId: "2",
    type: "daily_change",
    threshold: 5,
    enabled: true,
    triggered: true,
    lastTriggeredAt: "2026-08-31T01:25:00Z",
  },
  {
    id: "alert-3",
    cardId: "4",
    type: "volume_spike",
    threshold: 200,
    enabled: true,
    triggered: false,
  },
  {
    id: "alert-4",
    cardId: "10",
    type: "trade_rumor",
    enabled: true,
    triggered: false,
  },
  {
    id: "alert-5",
    cardId: "15",
    type: "signing",
    enabled: true,
    triggered: true,
    lastTriggeredAt: "2026-08-31T00:40:00Z",
  },
  {
    id: "alert-6",
    cardId: "8",
    type: "cohort_change",
    enabled: true,
    triggered: false,
  },
];

export const brands = [
  {
    name: "Topps",
    authorization: "NBA/NBPA 官方授权期：2025—26 赛季起",
    lines: [
      "Topps Basketball",
      "Topps Chrome Basketball",
      "Topps Finest",
      "Topps Midnight",
      "Topps NOW NBA",
      "Topps Hoops",
      "Rookie Debut Patch",
      "NBA Match Attax",
    ],
  },
  {
    name: "Panini",
    authorization: "现代存量卡主要覆盖：2009—2025",
    lines: [
      "Prizm",
      "Select",
      "Donruss Optic",
      "Mosaic",
      "National Treasures",
      "Flawless",
      "Immaculate",
      "Contenders",
      "Court Kings",
      "Donruss",
      "Hoops",
      "Spectra",
      "Origins",
      "One and One",
    ],
  },
  {
    name: "历史品牌",
    authorization: "兼容历史产品",
    lines: ["Upper Deck", "Fleer", "SkyBox", "Bowman", "Topps 历史产品"],
  },
];

export function getPlayer(id: string) {
  return players.find((item) => item.id === id);
}
export function getCard(id: string) {
  return cards.find((item) => item.id === id);
}
export function getTeam(idOrSlug: string) {
  return teams.find((item) => item.id === idOrSlug || item.slug === idOrSlug);
}
export function getPlayerCards(playerId: string) {
  return cards.filter((item) => item.playerId === playerId);
}
export function getCardSales(cardId: string) {
  return sales.filter((item) => item.cardId === cardId);
}
